/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.0.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.ringzero.controller.user.api;

import com.example.ringzero.controller.user.model.Result;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;

import javax.servlet.http.HttpServletRequest;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-01-07T14:06:14.144539400+07:00[Asia/Bangkok]")
@Validated
@Api(value = "users", description = "the users API")
public interface UsersApi {

    default UsersApiDelegate getDelegate() {
        return new UsersApiDelegate() {};
    }

    /**
     * GET /users : Get User Info
     * Retrieve the information of the user with the matching seed.
     *
     * @param seed  (required)
     * @return User Found (status code 200)
     *         or User Not Found (status code 404)
     */
    @ApiOperation(value = "Get User Info", nickname = "getUserBySeed", notes = "Retrieve the information of the user.", response = Result.class, tags={  })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "User Found", response = Result.class),
            @ApiResponse(code = 404, message = "User Not Found") })
    @GetMapping(
            value = "/users",
            produces = { "application/json" }
    )
    default ResponseEntity<Result> getUser(HttpServletRequest request) {
        return getDelegate().getUser(request);
    }

}
